#!/usr/bin/env bash

# source bash profile to get environment variables set
[ -f "$HOME/.bash_profile" ] && source "$HOME/.bash_profile"

if ! dscl . -read "$HOME" UserShell | grep -q -E "zsh"; then
  # set default shell to zsh
  chsh -s /bin/zsh $USER
fi


# Install Daptiv Projects --------------
SETUP_SCRIPT="$HOME/.daptiv-dotfiles/projects/setup"

# TTM -----
if [ -f "$SETUP_SCRIPT" ]; then
    bash "$SETUP_SCRIPT" ttm
    bash "$SETUP_SCRIPT" new-feature-popup
fi

